[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API passthrough to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Dynamic sitemap served by a Netlify Function
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
  force = true

# Serve robots.txt as a static file
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Remove trailing slashes (normalize URLs)
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true

# /index.html -> /
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

# SPA fallback — KEEP THIS LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ---------- Caching for static assets ----------
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ---------- Security headers ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# ---------- Noindex for previews (safe staging) ----------
[context.deploy-preview]
  [[context.deploy-preview.headers]]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex, nofollow"

[context.branch-deploy]
  [[context.branch-deploy.headers]]
    for = "/*"
    [context.branch-deploy.headers.values]
      X-Robots-Tag = "noindex, nofollow"
