[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# API must come BEFORE the SPA catch-all
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
