[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API passthrough
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Canonical host: www -> apex (flip if you prefer www)
[[redirects]]
  from = "https://www.aboveandbelowadventuresjo.com/*"
  to = "https://aboveandbelowadventuresjo.com/:splat"
  status = 301
  force = true

# Serve these files as-is (so SPA doesn't catch them)
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# Remove trailing slashes
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true

# /index.html -> /
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

# SPA fallback — KEEP LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ---------- Caching ----------
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ---------- Security ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# ---------- Noindex for previews ----------
[context.deploy-preview]
  [[context.deploy-preview.headers]]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex, nofollow"

[context.branch-deploy]
  [[context.branch-deploy.headers]]
    for = "/*"
    [context.branch-deploy.headers.values]
      X-Robots-Tag = "noindex, nofollow"
